name: Build and Publish Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set repo name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}:latest
          dockerfile: Dockerfile

      - name: Read package.json
        uses: zvonimirsun/read-package-version-actions@v2
        id: package-version

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}:${{ steps.package-version.outputs.version }}
          dockerfile: Dockerfile

      - name: Update to portainer
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.PORTAINER_UPDATE }}
          method: 'POST'
          preventFailureOnNoResponse: "true"
